// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

// GetStock provides a mock function with given fields: ctx, productID
func (_m *InventoryRepository) GetStock(ctx context.Context, productID string) (int32, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int32, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int32); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReserveStock provides a mock function with given fields: ctx, productID, quantity
func (_m *InventoryRepository) ReserveStock(ctx context.Context, productID string, quantity int32) (bool, error) {
	ret := _m.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for ReserveStock")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) (bool, error)); ok {
		return rf(ctx, productID, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) bool); ok {
		r0 = rf(ctx, productID, quantity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32) error); ok {
		r1 = rf(ctx, productID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
