// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/shestoi/GoBigTech/services/order/internal/repository"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *OrderRepository) GetByID(ctx context.Context, id string) (repository.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 repository.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingOutboxEvents provides a mock function with given fields: ctx, limit
func (_m *OrderRepository) GetPendingOutboxEvents(ctx context.Context, limit int) ([]repository.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOutboxEvents")
	}

	var r0 []repository.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]repository.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []repository.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleAssemblyCompletedTx provides a mock function with given fields: ctx, eventID, eventType, occurredAt, orderID
func (_m *OrderRepository) HandleAssemblyCompletedTx(ctx context.Context, eventID string, eventType string, occurredAt time.Time, orderID string) (bool, int64, error) {
	ret := _m.Called(ctx, eventID, eventType, occurredAt, orderID)

	if len(ret) == 0 {
		panic("no return value specified for HandleAssemblyCompletedTx")
	}

	var r0 bool
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, string) (bool, int64, error)); ok {
		return rf(ctx, eventID, eventType, occurredAt, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, string) bool); ok {
		r0 = rf(ctx, eventID, eventType, occurredAt, orderID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, string) int64); ok {
		r1 = rf(ctx, eventID, eventType, occurredAt, orderID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, time.Time, string) error); ok {
		r2 = rf(ctx, eventID, eventType, occurredAt, orderID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkOutboxEventFailed provides a mock function with given fields: ctx, eventID, errMsg
func (_m *OrderRepository) MarkOutboxEventFailed(ctx context.Context, eventID string, errMsg string) error {
	ret := _m.Called(ctx, eventID, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for MarkOutboxEventFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, eventID, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkOutboxEventSent provides a mock function with given fields: ctx, eventID
func (_m *OrderRepository) MarkOutboxEventSent(ctx context.Context, eventID string) error {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOutboxEventSent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetOutboxEventPending provides a mock function with given fields: ctx, eventID
func (_m *OrderRepository) ResetOutboxEventPending(ctx context.Context, eventID string) error {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ResetOutboxEventPending")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, order
func (_m *OrderRepository) Save(ctx context.Context, order repository.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveWithOutbox provides a mock function with given fields: ctx, order, eventID, eventType, occurredAt, payload, topic
func (_m *OrderRepository) SaveWithOutbox(ctx context.Context, order repository.Order, eventID string, eventType string, occurredAt time.Time, payload []byte, topic string) error {
	ret := _m.Called(ctx, order, eventID, eventType, occurredAt, payload, topic)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Order, string, string, time.Time, []byte, string) error); ok {
		r0 = rf(ctx, order, eventID, eventType, occurredAt, payload, topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
