// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ProcessedEventsStore is an autogenerated mock type for the ProcessedEventsStore type
type ProcessedEventsStore struct {
	mock.Mock
}

// IsProcessed provides a mock function with given fields: ctx, eventID
func (_m *ProcessedEventsStore) IsProcessed(ctx context.Context, eventID string) (bool, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IsProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkProcessed provides a mock function with given fields: ctx, eventID, ttl
func (_m *ProcessedEventsStore) MarkProcessed(ctx context.Context, eventID string, ttl time.Duration) error {
	ret := _m.Called(ctx, eventID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, eventID, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProcessedEventsStore creates a new instance of ProcessedEventsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessedEventsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessedEventsStore {
	mock := &ProcessedEventsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
