// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

// ReserveStock provides a mock function with given fields: ctx, productID, quantity
func (_m *InventoryClient) ReserveStock(ctx context.Context, productID string, quantity int32) error {
	ret := _m.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for ReserveStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) error); ok {
		r0 = rf(ctx, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
